/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.joker.test.hello_mk;

public final class NumbersUnSafe {
  public final static int ONE_UNSAFE = UnixJNI.ONE_UNSAFE_get();
  public final static int TWO_UNSAFE = UnixJNI.TWO_UNSAFE_get();
  public final static int THREE_UNSAFE = UnixJNI.THREE_UNSAFE_get();
  public final static int FOUR_UNSAFE = UnixJNI.FOUR_UNSAFE_get();
}

