/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.joker.test.hello_mk;

public enum NumbersJava {
  ONE_JAVA(UnixJNI.ONE_JAVA_get()),
  TWO_JAVA(UnixJNI.TWO_JAVA_get()),
  THREE_JAVA,
  FOUR_JAVA;

  public final int swigValue() {
    return swigValue;
  }

  public static NumbersJava swigToEnum(int swigValue) {
    NumbersJava[] swigValues = NumbersJava.class.getEnumConstants();
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (NumbersJava swigEnum : swigValues)
      if (swigEnum.swigValue == swigValue)
        return swigEnum;
    throw new IllegalArgumentException("No enum " + NumbersJava.class + " with value " + swigValue);
  }

  @SuppressWarnings("unused")
  private NumbersJava() {
    this.swigValue = SwigNext.next++;
  }

  @SuppressWarnings("unused")
  private NumbersJava(int swigValue) {
    this.swigValue = swigValue;
    SwigNext.next = swigValue+1;
  }

  @SuppressWarnings("unused")
  private NumbersJava(NumbersJava swigEnum) {
    this.swigValue = swigEnum.swigValue;
    SwigNext.next = this.swigValue+1;
  }

  private final int swigValue;

  private static class SwigNext {
    private static int next = 0;
  }
}

