/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.joker.test.hello_mk;

public interface UnixConstants {
  public final static int MAX_WIDTH = UnixJNI.MAX_WIDTH_get();
  public final static int MAX_HEIGHT = UnixJNI.MAX_HEIGHT_get();
  public final static int MAX_WIDTH_COMPILE = 640;
  public final static int MAX_HEIGHT_COMPILE = 320;
  public final static int ONE = UnixJNI.ONE_get();
  public final static int TWO = UnixJNI.TWO_get();
  public final static int THREE = UnixJNI.THREE_get();
  public final static int FOUR = UnixJNI.FOUR_get();

}
