/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.joker.test.hello_mk;

public class Unix implements UnixConstants {
  public static void setCounter(int value) {
    UnixJNI.counter_set(value);
  }

  public static int getCounter() {
    return UnixJNI.counter_get();
  }

  public static void inc_counter() {
    UnixJNI.inc_counter();
  }

  public static int getReadOnly() {
    return UnixJNI.readOnly_get();
  }

  public static void setReadWrite(int value) {
    UnixJNI.readWrite_set(value);
  }

  public static int getReadWrite() {
    return UnixJNI.readWrite_get();
  }

  public static void drawByPointer(Point p) {
    UnixJNI.drawByPointer(Point.getCPtr(p), p);
  }

  public static void drawByReference(Point p) {
    UnixJNI.drawByReference(Point.getCPtr(p), p);
  }

  public static void drawByValue(Point p) {
    UnixJNI.drawByValue(Point.getCPtr(p), p);
  }

  public static void func(int a, int b, int c) {
    UnixJNI.func__SWIG_0(a, b, c);
  }

  public static void func(int a, int b) {
    UnixJNI.func__SWIG_1(a, b);
  }

  public static void func(double d) {
    UnixJNI.func__SWIG_2(d);
  }

  public static void func(int i) {
    UnixJNI.func__SWIG_3(i);
  }

  public static long getuid() {
    return UnixJNI.getuid();
  }

}
